### ISSUE TITLE
Minor typos

### ISSUE THREAD

**Issue by yvoyer** [dddinphp/ddd-in-php-book-issues#1]
I found typos while reading the book, I'll add some as I read along.
- 7.1.1 (p.117) "Each time the model grows, it will **proably** need even more infrastructure..."
- 7.1.1 (p.117) "is to define a module for each of the **techincal** concern into the bounded context."
- 7.2.2 (p.123): "between classes and **phsycal** PHP files
- 7.2.2 (p.123): "**Te** class name for the Bill entity"
- 9.2.0 (p125): "is a creational pattern that allows subclasses **(missing to?)** decide how to create objects"
- 10.3.0 (p.138): "If for example we have the following Domain **Modal**" (Should it be Model?)

Keep up the good work, great book.

**Comment by carlosbuenosvinos** [comment]
Thanks for the feedback. I have fixed the problems and republished again the book. Thanks again!
