### ISSUE TITLE
Inconsistencies

### ISSUE THREAD

**Issue by nicoSWD** [dddinphp/ddd-in-php-book-issues#10]
#### 4. Entities

All code examples in this book appear to follow PSR-2 coding standards, except for the code in the **Entities** and **Modules** chapters.

``` php
{
    // ...

    public function identificationNumber() {
        return $this->identificationNumber;
    }

    public function firstName() {
        return $this->firstName;
    }

    public function lastName() {
        return $this->lastName;
    }
}
```
#### 5.2 Application Services

The class `SignInUserService` mixes the concepts of _Login_ and _Sign up_. An exception called `UserAlreadyExistsException` should be thrown during registration, not logging in. And the new `User` instance should not be persisted?

The same problems appears in **9.3.2 Building Aggregates**.
#### 5.4 Domain Services With Multiple Implementations

The concepts of hashing and encrypting are mixed here. All references to encryption should be changed to hashing. They're two very different things.
#### Other
- Sometimes, closures have a space between the `function` keyword and the opening parentheses, and sometimes they don't. `function()` vs. `function ()`.
- Mixed array syntax. `[]` vs. `array()`.
- Sometimes, getters are prefixed with `get`, and sometimes they're not. `getCountry()` vs. `userId()`.
- "object-orientated" is sometimes spelled "object-orientated", and sometimes "Object-Orientated".

**Comment by carlosbuenosvinos** [comment]
Entities code are now in PSR2

**Comment by carlosbuenosvinos** [comment]
Modules are in PSR2

**Comment by keyvanakbary** [comment]
@nicoSWD hey, we are really sorry for not addressing these for a while, we've been a little bit busy. We've fixed them all. Great feedback, thanks! :)
