### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by luisrovirosa** [dddinphp/ddd-in-php-book-issues#11]
Page 37. 2.4.

"This option is based on a design principle, named Command-Query Segregation CQS, defined by Bertrand Meyer and from this borns another new architectural pattern named Command-Query Responsability Segregation **and** defined by Greg Young."

I think the **and** should be a comma like in the previous one.

**Comment by carlosbuenosvinos** [comment]
Fixed already by Henry on December, 1st. Thanks!
