### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by luisrovirosa** [dddinphp/ddd-in-php-book-issues#12]
2.5 page 29.

"This is what it may look like an implementation of the PostRepository that makes use of an
eventstore to save all the events published by an aggregate, and now we need a way to **retore**
an aggregate from its events history. For this it come handy the reconstitute method implemented
by the Post aggregate to be used to rebuild a blog post state from the events it triggered."

Should be **restore**

**Comment by carlosbuenosvinos** [comment]
Fixed, thanks!
