### ISSUE TITLE
Inconsistency?

### ISSUE THREAD

**Issue by luisrovirosa** [dddinphp/ddd-in-php-book-issues#13]
3.4.5 page 42

"Sharing the same Value Object can be risky, **if one is altered**, both will reflect the change. This
behaviour can be considered an unexpected side-effect. For example, if Carlos was hired on February,
20th, and we know that Christian was also hired on the same day, we may set Christian’s hire date to
be the same instance as Carlos’s. If Carlos then changes the month in his hire date to May, Christian’s
hire date changes too. Whether it is correct or not, it is not what people expect.
Due to the problems highlighted in this example when holding a reference to a Value Object, rather
than modifying its value, it is recommended instead to replace the object as a whole."

I agree with the conclusion but I think that the reason is that you can't change a value object, then you should replace the hole instance. Otherwise you will break an important rule of a value object: **immutability**. You should not be able to modify a value object.

What do you think?

**Comment by carlosbuenosvinos** [comment]
Luis, what we're trying to say is that if you two entities point to the same instance of value object, regardless of two different ones, thought can have the "same value", when such Value Object is replaced via one of the instances, the other also changes (cause' is pointing to the same one). Does is make sens?
