### ISSUE TITLE
 Page 67 | Ch3 | Page 52 - Typos

### ISSUE THREAD

**Issue by tomjowitt** [dddinphp/ddd-in-php-book-issues#15]
The "Why Doctrine" info box contains a few typos and grammar errors:

Doctrine10 is a great ORM. It solves 80% of the requirements a PHP application faces. It
has a great community and a correctly-tuned **set-up** can **perform** the same or even better
than a bespoke ORM (without **losing** maintainability). We recommend using Doctrine in
most cases when dealing with Entities and business logic. It will save you **a lot of time and
headaches**.

**Comment by carlosbuenosvinos** [comment]
Fixed, thanks!

**Comment by carlosbuenosvinos** [comment]
You're now in the Acknowledgements, thanks!

**Comment by tomjowitt** [comment]
Awesome thanks. It's a great book so far.
