### ISSUE TITLE
Clarification of "Sign In"

### ISSUE THREAD

**Issue by jwondrusch** [dddinphp/ddd-in-php-book-issues#16]
In the _Services_ and _Domain Events_ chapters (maybe others, I'm still going through the book), the **SignIn** service is used as an example.

Using **Registration** as a name for the service would improve clarification, as **SignIn** can easily be confused with **Login**.

**Comment by kesar** [comment]
+1 with naming.

also in the code there is a mistake:

```
$user = $this->userRepository->userOfEmail($request->email);
        if (!$user) {
            throw new UserAlreadyExistsException();
        }
```

condition shouldnt be !$user, it should be just $user

**Comment by carlosbuenosvinos** [comment]
Thanks! Fixed the typo in the code. We're working on the SignIn issue.

**Comment by carlosbuenosvinos** [comment]
@jwondrusch could you give me your full name?

**Comment by jwondrusch** [comment]
@carlosbuenosvinos Sure, it is Jonathan Wondrusch.

**Comment by carlosbuenosvinos** [comment]
Could you please check the new version of the book?

**Comment by keyvanakbary** [comment]
@jwondrusch Fixed all references to `SignIn` (Login) to `SignUp` (Registration), thanks man :)

@kesar that code is actually correct, the sign up service tries to find an existing user with that email, **if it exists**, then it rejects the registration.

Thanks both and sorry for the delay.
