### ISSUE TITLE
Repository pattern with Filters, Order,Limit and Offset

### ISSUE THREAD

**Issue by josecelano** [dddinphp/ddd-in-php-book-issues#19]
Hi, I like very much the book. I am starting a new project using some of the patterns described in the book. I have seen a lot of DDD samples which convert domain entities to DTOs to be consumed by the view. I like that approach but I do not know how to deal with reports. If you have a lot of view (for different user roles, and which requiring joins) using the Repository pattern to get entities and them convert them to nested DTO's seems to be too much complexity. For exmaple if I want to show a table and allow the user to filter and sort by any of the columns I have to create a lot of Repository methods or create only one 'search' method and pass a list of filtering,paging, sorting options. I have not found info about how to do that. Some people said DDD is not for reporting and I should go directly to database: in my case using LAravel DB class or if you are using Doctrine the entity manager repository. But that seems to be coupling to database. I would like to see more samples about how to do that in the book. I think is a very common problem. All DDD samples I have seen are too simple.

I have asked the same in the DDD google group with a code sample:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/dddinphp/qGwa2c03F88/8KVVga1pDAAJ

In your book sample, my problem would be, waht happens if I want a list of posts filter by poser creation date and sorted by post id, and so on. Should I create a repository methdod for each case. I do not think so.

I have read some blog post that saids paging, filtering and sorting must be in the Presentation Layer. Should I get all blog posts and do paging, filtering and sorting with UI helpers classes. I think that is reinvent the wheel as that job can be easily do by SQL, ORM, etc.

**Comment by theUniC** [comment]
Hi Jose,

DDD is not for _reporting_ as long as your core domain it's not about _reporting_. If the ubiquitous language of the core domain of your application is about reporting it should be tackled as any other domain concern.

Having said that, normally _reporting_ (understanding _reporting_ as all the view and presentation concerns) it is not usually the core domain and DDD in general has little to do with reading and presenting data. So it doesn't fit well on CRUD-ish applications.

But If your application anyway needs a high degree of reads and cluttering your repositories with a lot of different read methods and defining **[Assemblers](http://martinfowler.com/eaaCatalog/dataTransferObject.html)** to transform the domain objects to plain DTO's is not an option you should consider split reads and writes in an CQRS-style architecture. By doing this you could easily achieve the flexibility the application needs to read data as the read model used to present data it's completely independent of the write model, mainly used to model the domain behaviour.

Christian.

**Comment by josecelano** [comment]
Thank you for you response @theUniC and sorry for my response delay. Finally I am using a `QueryObject` pattern to store query specification and I have added a method to the repository class which acepts that query object.

```
<?php

class DoctrineRepository
{
    public function findAllProjects(QueryObject $queryObject)
    {
        ...
    }
}

class QueryObject
{
    /**
     * @var Criteria[]
     */
    private $criteria;

    /**
     * @var Order[]
     */
    private $orders;

    /**
     * @var int
     */
    private $offset;

    /**
     * @var int
     */
    private $limit;

    /**
     * QueryObject constructor.
     */
    public function __construct()
    {
        $this->criteria = array();
        $this->orders = array();
        $this->offset = 0;
        $this->limit = -1;
    }

    /**
     * @param Criteria $criteria
     * @return $this
     */
    public function addCriteria(Criteria $criteria)
    {
        $this->criteria[] = $criteria;
        return $this;
    }

    /**
     * @param Order $order
     * @return $this
     */
    public function addOrder(Order $order)
    {
        $this->orders[] = $order;
        return $this;
    }

    /**
     * @param int $limit
     * @param int $offset
     * @return $this
     * @throws \Exception
     */
    public function setLimitAndOffset($limit, $offset)
    {
        Assertion::min($limit, -1);
        Assertion::min($offset, 0);

        if ($limit == -1 && $offset > 0) {
            throw new \Exception('Offset requires limit > 0.');
        }

        $this->limit = $limit;
        $this->offset = $offset;
        return $this;
    }

    /**
     * @return Criteria[]
     */
    public function getCriteria()
    {
        return $this->criteria;
    }

    /**
     * @return int
     */
    public function getLimit()
    {
        return $this->limit;
    }



    /**
     * @return int
     */
    public function getOffset()
    {
        return $this->offset;
    }

    /**
     * @return Order[]
     */
    public function getOrders()
    {
        return $this->orders;
    }
}
```

This way this method can resolve a lot of different basic queries. Internally the repository class maps that query object to a Doctrine query using Doctrine query builder.
