### ISSUE TITLE
Too Doctrine-centered

### ISSUE THREAD

**Issue by keyvanakbary** [dddinphp/ddd-in-php-book-issues#2]
Suggestion by Marc Aube [here](http://marcaube.ca/2015/05/specifications/)

> If I can voice a criticism, it was a bit too Doctrine-centered

**Comment by carlosbuenosvinos** [comment]
Doctrine is probably the most important ORM in the PHP World, and also really well-known. I use it a lot and I consider that it's a good candidate for explaining existing ORM based solutions. We'll try to show how to solve the problems also in a custom ORM.
