### ISSUE TITLE
2.2.2.1 The Model - Repository class

### ISSUE THREAD

**Issue by jaymecd** [dddinphp/ddd-in-php-book-issues#20]
There is a typo on page 12 (2.2.2.1 The Model) in code snippet:

``` php
class PostRepository {
    ...
    public static function add(Post $post) {
        $this->db->beginTransaction();
        try {
            $stm = $db->prepare(
                'INSERT INTO posts (title, content) VALUES (?, ?)'
            );
        ...
        }
    }
    ...
}
```

`$this->db` - wrong call: instance property from static scope.

UPD:

Actually `PostService` snippet (same page) requires repository instance:

``` php
(new PostRepository())->add($post);
```

So repository should not have static method and convert `$db->...` calls to `$this->db->...` ones.

**Comment by keyvanakbary** [comment]
@jaymecd All fixed! Thanks :)
