### ISSUE TITLE
Layout of Service Types

### ISSUE THREAD

**Issue by nubeiro** [dddinphp/ddd-in-php-book-issues#22]
At **5.1 Introduction** the different types would be easier to understand if you uses some borders on the table. 
Currently Application services are described with two paragraphs separated by carriage returns, making it look like first row is vertically aligned to the top, while Domain services also get two paragraphs. 

I've checked the rendering in PDF file (where it's less confusing) but rendering in kindle and ibook (from epub format) can be confusing due to lack of clear separation.

**Comment by keyvanakbary** [comment]
Nice suggestion. Fixed! Thanks :)
