### ISSUE TITLE
Missing infrastructure service examples?

### ISSUE THREAD

**Issue by nubeiro** [dddinphp/ddd-in-php-book-issues#24]
In chapter 5, Application Services and Domain Services are explained in great detail. Infrastructure services are explained only at the introduction and in the wrap up.

For the sake of completeness, could you add also infrastructure service examples?

**Comment by theUniC** [comment]
Hi,

First of all thanks for taking the time to open and reporting the issue. We're really glad to see any feedback that let us improve the book.

In response to your question I should say that they are already explained in the chapters **5.4 - Domain Services with multiple implementations** and **5.4.1 - An issue on Code Reuse** (specially on that chapter). However, I may agree that it's not visible enough and that we could make the _infrastructure services_ concept more clear on those chapters.

Best,
Christian.

**Comment by nubeiro** [comment]
Thanks a lot for the reply. 
Please bear in mind that I consider myself a DDD learner (still in progress :-D). 
If one of the goals of the book is to help DDD newbies, I suggest that you do make a clear distinction between what is a Domain Service vs an Infrastructure Service. 

Maybe changing the following: 

> “Opting for this choice allows us to have multiple implementations of the domain service interface, each responsible for handling different encryption mechanisms. ”

for this: 

> “Opting for this choice allows us to have multiple **infrastructure service** implementations of the domain service interface, each responsible for handling different encryption mechanisms. ”

or maybe this:

> “Opting for this choice allows us to have multiple implementations of the domain service interface **at the infrastructure service layer**, each responsible for handling different encryption mechanisms. ”

Would avoid confusions for newbies like me. 

Section 5.4.1 does not mention at all in which layer (domain? infrastructure?) those changes should go. Maybe adding a short explanation at the end of 5.4.1, after BasicPasswordEncryption and Md5PasswordEncryption would help. If I understood correctly, the `interface PasswordEncryption` should be in the Domain layer and the `BasicPasswordEncryption` and `Md5PasswordEncryption` implementations should be in the Infrastructure layer?

**Comment by theUniC** [comment]
Exactly. That's why I agree that the concept it's not clear enough. I like
your suggestions. Late on this week I'll review them along with the chapter
itself and see how it can be improved, and make the concepts really clear.

Thanks again!

Best,
Christian.

2016-03-08 13:02 GMT+01:00 Raúl Araya notifications@github.com:

**Comment by theUniC** [comment]
We have published a new version with adjustments on the domain services chapter, to make clear the infrastructure services concept.

**Comment by keyvanakbary** [comment]
I guess this closes the issue :)

**Comment by nubeiro** [comment]
Thanks a lot :+1:
