### ISSUE TITLE
Preface suggestions

### ISSUE THREAD

**Issue by nubeiro** [dddinphp/ddd-in-php-book-issues#25]
Since last update made it to 90% of the book I am reading it again. 
Let me first say thank you for taking the effort to write a book on DDD using PHP. 
Please see below my suggested changes for preface, I'm using bold typeface to highlight changes. 

> "Entities are the **identified by identity** building blocks of DDD.”

Maybe would make more sense using dashes:

> "Entities are the **identified-by-identity** building blocks of DDD.”

---

> “We’ll also review the annotations yes-or-no **flame** and the different strategies for generating identity.”

Maybe  

> “We’ll also review the annotations yes-or-no **flame war** and the different strategies for generating identity.”

---

> “With so many tactical building **block** it’s a bit difficult to know where to place them in code. ”

Maybe 

> “With so many tactical building **blocks** it’s a bit difficult to know where to place them in code. ”

---

> “We’ll see a practical scenario where two aggregates become one when adding a business rule and how the rest of the objects must be **refactor**.”

Maybe

> “We’ll see a practical scenario where two aggregates become one when adding a business rule and how the rest of the objects must be **refactored**.”

**Comment by keyvanakbary** [comment]
Than **you** for the interest and your lovely contributions. We took all your suggestions, thanks! :)
