### ISSUE TITLE
Chapter 11 suggestions for changes

### ISSUE THREAD

**Issue by nubeiro** [dddinphp/ddd-in-php-book-issues#27]
Once again, thanks for writing a much needed book for PHP developers. 
The following are mostly typos I've found when re-reading chapter 11. I'm grouping all them in one issue to avoid flooding you with issues. 

Bold typeface is used to highlight suggested changes. 

> “The later approach, sending a DTO, **bring** some interesting features to the
> table. ”

Maybe

> “The later approach, sending a DTO, **brings** some interesting features to the
> table. ”
## 
### Section 11.2.1 Building Application Service Requests

code snippets are missing
syntax highlighting.
### Section 11.3

> “ At a high level then we **need if** there is an existing user with that email
> already.”

Maybe

> “ At a high level then we **need to check if** there is an existing user with that email
> already.”
## 

> “This is not only **inefficient it** also spreads duplication across
> controllers.”

Maybe

> “This is not only **inefficient but it** also spreads duplication across
> controllers.”

Or

> “This is not only **inefficient, it** also spreads duplication across
> controllers.”
### Section 11.3.3.1 One Class per Application Service

> “It’s easier to implement a common Application Service contract, making class
> decoration easier (check out transactions in repositories chapter). ”

Could you add a link to that specific chapter?

> “There is greater cohesion with the dependencies as all dependencies are
> dedicated the Application Service."

I had a hard time with this one, looks like it's missing something:
"all dependencies are dedicated **to** the Application Service"?
### Section 11.3.3.2 Multiple Application Service Methods per Class

> “There are cases **where might** be a good idea to group **of** cohesive Application
> Services under the same class”

Maybe

> “There are cases **in which it might** be a good idea to group cohesive Application
> Services under the same class”

or maybe

> “**Sometimes it might** be a good idea to group cohesive Application
> Services under the same class”

---

> “Some services will require different dependencies and you’ll end up with
> Application Services depending on things **that** they don’t need. ”

Maybe

> “Some services will require different dependencies and you’ll end up with
> Application Services depending on things they don’t need. ”
### Section 11.3.4 Returning Values

contains code snippets that are missing syntax
highlighting.

> “This will allow the delivery mechanism to bypass the Application Layer and
> interact directly with **the the** domain.”

Extra 'the' must be removed:

> “This will allow the delivery mechanism to bypass the Application Layer and
> interact directly with **the** domain.”
### Section 11.3.4.1 DTO from Aggregate Instances

> “Let’s allow the client to define how to **built** the DTO by passing a specific
> DTO assembler.”

Maybe

> “Let’s allow the client to define how to **build** the DTO by passing a specific
> DTO assembler.”
### Section 11.3.4.2 Data Transformers

> “Usually the product information is served through a web interface (HTML) but
> we might be interested in **offer** other formats like XML, JSON or CSV. ”

Maybe

> “Usually the product information is served through a web interface (HTML) but
> we might be interested in **offering** other formats like XML, JSON or CSV. ”
## 

> “Wondering how **would look like the XML or CSV one**?”

Maybe

> “Wondering how **the XML or CSV one would look like**?”
## 

> “We think the long-term vision **will worth** the investment. ”

Maybe:

> “We think the long-term vision **will be worth** the investment. ”
## 

> “Using DTO’s or Data Transformers **allow** you to evolve your model freely
> without having to think about breaking the layout all the time.”

Maybe:

> “Using DTO’s or Data Transformers **allows** you to evolve your model freely
> without having to think about breaking the layout all the time.”
### Section 11.4 Testing

> “ If creating a user fires a user registered event, **assuring** it has been
> triggered might be a good idea.”

Maybe

> “ If creating a user fires a user registered event, **ensuring** it has been
> triggered might be a good idea.”
### Section 11.5 Transactions

> “Transactions **are detail** related with the persistence mechanism. ”

Maybe

> “Transactions **are an implementation detail** related with the persistence mechanism. ”
### Section 11.7 Domain Events

> “ There are situations where you’ll have to be **explicitly** and configure the
> listener before executing the Application Service.”

Maybe

> “ There are situations where you’ll have to be **explicit** and configure the
> listener before executing the Application Service.”
### Section 11.8 Command handlers

> “**Wouldn’t be** great if we had a mechanism to link all the Application Services
> and then based on the Request execute the correct one?”

Maybe

> “**Wouldn’t it be** great if we had a mechanism to link all the Application Services
> and then based on the Request execute the correct one?”
## 

> “Well, that is actually what a **Comment** Bus is.”

Maybe

> “Well, that is actually what a **Command** Bus is.”
### Section 11.8.1 Tactician Library and Other Options

> “It’s specially convenient for Application Services but you could use any kind
> of input **tho**.”

I don't know if it should be **too** or **though**.
## 

> “Answer the user fast and **let the** know once the job is done.”

Maybe

> “Answer the user fast and **let him** know once the job is done.”

Or maybe

> “**Send an answer** the user fast and **let him** know once the job is done.”

**Comment by keyvanakbary** [comment]
Woah, you are on fire man LOL. Fixed them all. You are now part of the Acknowledgements :+1: :tada:

**Comment by nubeiro** [comment]
Awesome, thanks a lot!
