### ISSUE TITLE
'assertNotEmpty' undefined function and its use...

### ISSUE THREAD

**Issue by hub20xx** [dddinphp/ddd-in-php-book-issues#29]
Page 11 (version 2016-02-09):
in the `Post` class, the function `assertNotEmpty` is not defined and also in `setContent` it is used to check if the `$title` is not empty, instead of `$content`, hence 2 questions:
- what `assertNotEmpty` would be doing? I can only think about throwing an exception in order to force the use of a title and a content
- shouldn't `assertNotEmpty` be used to check that `$content` is not empty in `setContent`?

Here is the code:

```
class Post
{
    private $title;
    private $content;

    public static function writeNewFrom($title, $content)
    {
        return new static($title, $content);
    }

    private function __construct($title, $content)
    {
        $this->setTitle($title);
        $this->setContent($content);
    }

    private function setTitle($title)
    {
        $this->assertNotEmpty($title);
        $this->title = $title;
    }

    private function setContent($content)
    {
        $this->assertNotEmpty($content);
        $this->content = $content;
    }

}
```

**Comment by keyvanakbary** [comment]
Fixed! :+1:
