### ISSUE TITLE
Typo in SQL insert

### ISSUE THREAD

**Issue by hub20xx** [dddinphp/ddd-in-php-book-issues#34]
Page 24 (Version 2012-03-26):

SQL queries to populate the database causing error (at least in MySQL).

For example running 
`INSERT INTO single_post_with_comments(1, 1, "Layered architecture", "Lorem ipsum\
dolor sit amet, ...", NOW(), "Lorem ipsum dolor sit amet, ...");`
returns 
`ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '1, 1, "Layered architecture", "Lorem ipsum
dolor sit amet, ...", NOW(), "Lorem i' at line 1`

Looks like to me that there's a `VALUES` missing, because running the following query works:
`INSERT INTO single_post_with_comments VALUES (1, 1, "Layered architecture", "Lorem ipsum\
dolor sit amet, ...", NOW(), "Lorem ipsum dolor sit amet, ...");`

As a side note, all the inserts put together in one call using `VALUES` as well:
`INSERT INTO single_post_with_comments VALUES 
(1, 1, "Layered architecture", "Lorem ipsum\
dolor sit amet, ...", NOW(), "Lorem ipsum dolor sit amet, ..."),
(2, 1, "Layered architecture", "Lorem ipsum\
dolor sit amet, ...", NOW(), "Lorem ipsum dolor sit amet, ..."),
(3, 2, "Hexagonal architecture", "Lorem ips\
um dolor sit amet, ...", NOW(), "Lorem ipsum dolor sit amet, ..."),
(4, 2, "Hexagonal architecture", "Lorem ips\
um dolor sit amet, ...", NOW(), "Lorem ipsum dolor sit amet, ..."),
(5, 3, "Command - Query Responsability Segg\
regation", "Lorem ipsum dolor sit amet, ...", NOW(), "Lorem ipsum dolor sit amet\
, ..."),
(6, 3, "Command - Query Responsability Segg\
regation", "Lorem ipsum dolor sit amet, ...", NOW(), "Lorem ipsum dolor sit amet\
, ...");`

**Comment by keyvanakbary** [comment]
@hub20xx Fixed! Thanks a lot :)
