### ISSUE TITLE
p177 sentences don't make sense

### ISSUE THREAD

**Issue by nealio82** [dddinphp/ddd-in-php-book-issues#38]
"So what’s a?"
"In the previous example, the amount of an Order must match the sum of amounts of all the Line Orders is an invariant."

**Comment by nealio82** [comment]
"If there is no invariant to protect, than means all single Entities perform
As you probably have done for the 90%"

**Comment by carlosbuenosvinos** [comment]
That's probably because the chapter is still WIP. But now, those sentences make sense.Thanks btw.
