### ISSUE TITLE
Use consistent ORM mapping

### ISSUE THREAD

**Issue by nealio82** [dddinphp/ddd-in-php-book-issues#40]
Early in the book you say that your preferred mapping method is XML and you provide some examples of this.

Then later, with no apparent reason or warning, you switch to yaml. In following the examples I had to translate the yaml to XML. It makes the book harder to use.

**Comment by carlosbuenosvinos** [comment]
I think it's interesting to show different approaches. We suggest to use XML, but there are developers that prefer YAML. I don't see a big problem.
