### ISSUE TITLE
Consider employing an English proof reader

### ISSUE THREAD

**Issue by nealio82** [dddinphp/ddd-in-php-book-issues#44]
While the book covers some important concepts and I've largely been able to follow along and make allowances for some errors in the code and explanations, I think the book could greatly benefit from being proof read professionally by someone who has English as their first language. At the moment it feels like there hasn't been any proof reading done at all, and I would say that the majority of pages have sentences which either don't quite sound right where they've been translated from languages with different grammatical constructs to English, or are just wrong and have to be ignored. It makes understanding the content a lot harder than it needs to be, and as we're covering rather advanced topics in PHP it should be presented as simply as possible.

Having spent money on the book it's disappointing to have to try to interpret concepts or submit issues on github. If the book had been free (as in beer) then it would have been far more acceptable to ask the community to help with proof reading. As I've paid for the book, I would kind-of expect the proof reading to have been done for me.

**Comment by theUniC** [comment]
First of all, thanks for taking the time to open an issue. We greatly appreciate your feedback and we're really glad to get any kind of feedback.

Indeed, we're really concerned about this. But the book is not ended yet. We prefer to end the book before sending it to review by professional native English speakers. Once we get done with the book, we plan to send it for review.

Thanks again for your feedback.

**Comment by nealio82** [comment]
Okie dokie. I have learned a fair amount from reading the book (I was looking for CQRS / ES examples in particular), but I think the learning could be made much more accessible with clearer English. Thanks for your quick reply.

**Comment by keyvanakbary** [comment]
Hey @nealio82, we actually have a couple of native speakers reviewing the book as we want to offer a good experience. You are right. As @theUniC already said, we plan to get some professional help on this. Building a book in Leanpub is a very iterative process, that's why the book is also cheaper at this stage. Fortunately, you'll get all the updates for free :)
We strive for excellence, take for granted that we'll do everything in our hand to improve the reading experience.

We really appreciate the time you've spent on giving us feedback. We'll fix all the issues you've reported. Thanks a lot!

**Comment by nealio82** [comment]
Great stuff :) I hope it doesn't sound like I was being overly negative in the ticket; I was just vocalising some thoughts. It's quite clear that you each know your stuff / have working knowledge of DDD in PHP but the writng style doesn't do your professional skills justice :S

**Comment by keyvanakbary** [comment]
@nealio82 no worries dude. We really appreciate sincere & honest feedback :)
