### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by reksc** [dddinphp/ddd-in-php-book-issues#47]
p. 198

> However, for the approach shown here, the code seems to work**s**.

... I think the code should seem to "work".

>  "Could be possible to break the rule of a User to have more than three wishes?"

Maybe "Could it be possible" or "Is it possible"?

I'm not sure if I should post English related issues, as you guys are / were looking for a professional editor (at least that's what I recall from my twitter stream).

Still this is an excellent read.

**Comment by carlosbuenosvinos** [comment]
We've found a professional editor that will be working on the book next week :). TYPOs are fixed. Thanks! You are now in the Acknowledgements.
