### ISSUE TITLE
New typos

### ISSUE THREAD

**Issue by reksc** [dddinphp/ddd-in-php-book-issues#48]
Below a list of some typos I noted down:

p. 35 - unnecessary whitespace

> private $eventS tore;

p. 81

> This kind of concept, have an identity that endures over the time. In PHP that would be plain old
> classes.

My English is far from perfect, but feels like the first sentence needs a correction. ("This is a concept of an identity that endures over the time", "The concept here is to have an identity that endures over time"?)

p. 217 - missing letter

> wishes property must be initialize**d** in the User constructor.

p. 218 - missing letter

> Look**s** like Business does not want a user to have more than 3 wishes. 

I updated the page numbers to match the latest book update (fantastic, by the way).

**Comment by carlosbuenosvinos** [comment]
Fixed, thanks
