### ISSUE TITLE
PostWasCreated event is missing implementation

### ISSUE THREAD

**Issue by serroba** [dddinphp/ddd-in-php-book-issues#55]
In 2.4.1 you create new instances of `PostWasCreated()` but although there is implementation for `PostWasCreated()` projector there is not the equivalent implementation of the Domain Event. I think it could add some clarity, in particular when using the same name for both (under different namespace), but they represent different things.

**Comment by keyvanakbary** [comment]
Wow, you were totally right. Very confusing. Renamed the projection implementations with the `Projection` suffix, so it becomes less confusing with plain Domain Events.

Thanks, I've included you in the acknowledgements! :)

**Comment by serroba** [comment]
Thanks!!! Was not expecting that ;)
