### ISSUE TITLE
Typo in section 4.7 (page 120) and page 109 wrong visibility

### ISSUE THREAD

**Issue by sstok** [dddinphp/ddd-in-php-book-issues#58]
## Typo in section 4.7 (page 120)

`14 new PostPlished(` this should be `PostPublished`

And on page 221 `PostUnplished(` this should be `PostUnpublished(`
## page 109

The `setToday` method is marked protected, while it's used in the test as a public method.

**Comment by carlosbuenosvinos** [comment]
Fixed. Thanks.
