### ISSUE TITLE
Display issue in page 143?

### ISSUE THREAD

**Issue by sstok** [dddinphp/ddd-in-php-book-issues#59]
The text after `In Domain-Driven Design, they are fundamental building blocks that help:` seems to be a list but it's not displayed as such.

**Comment by sstok** [comment]
Same goes for page 212.

**Comment by sstok** [comment]
And page 240, you may want to do a quick run trough all pages for rendering issues.

**Comment by carlosbuenosvinos** [comment]
Those we're fixed already.
