### ISSUE TITLE
Replaceability

### ISSUE THREAD

**Issue by DrSchimke** [dddinphp/ddd-in-php-book-issues#6]
Value Objects

Under replaceability you write _Sharing the same Value Object can be risky, if one is altered, both will reflect the change_, while at you emphasize somewhere else the _immutability_ as a key feature of value objects.

This seems to be a bit contradictorily.

Another related thing: I misread (so it is my fault) the `private` visibility of your setters, so I thought, it is public. I personally don't have private setters and make the assignment direct in constructor.

**Comment by marcaube** [comment]
> Another related thing: I misread (so it is my fault) the private visibility of your setters, so I thought, it is public. I personally don't have private setters and make the assignment direct in constructor.

That's what Vaughn Vernon calls self-encapsulation in the Red Book:

> "The constructor delegates instance variable assignment to its own internal attribute/property setters, which provide self-encapsulation for the variables. The self-encapsulation enables each setter to determine the appropriate contractual conditions for setting a portion of state."
> 
> Excerpt From: Vaughn Vernon. "Implementing Domain-Driven Design"

Basically, the private setters make sure your invariants are respected before making the assignment. That's where you'd place your guards clauses.

**Comment by DrSchimke** [comment]
Thanks for your clarification. I didn't have in mind this part from Vernon's book (need to reread is after finishing your book). I, for myself, often put my guards and invariant checkings directly to constructors, the there is no other code, which changes my properties... But, who cares.
