### ISSUE TITLE
Typo in Preface vii, Chapter 4: Entities

### ISSUE THREAD

**Issue by vhraban** [dddinphp/ddd-in-php-book-issues#61]
We’ll also a**cc**ess whether or not annotations are the best mapping approach for Entities and look at the different strategies for generating an identity.

should say

We’ll also a**ss**ess whether or not annotations are the best mapping approach for Entities and look at the different strategies for generating an identity.

**Comment by carlosbuenosvinos** [comment]
It was fixed. But still thanks. You're now in Acknowledgements.
