### ISSUE TITLE
page 31, broken link

### ISSUE THREAD

**Issue by vhraban** [dddinphp/ddd-in-php-book-issues#62]
For the next example, we will use the ampqlib PHP extension in combination with ReactPHP

ReactPHP is a link pointing to http://https//github.com/GeniusesOfSymfony/ReactAMQP while it should be http://https//github.com/GeniusesOfSymfony/ReactAMQP (note the missing : after https protocol )

**Comment by carlosbuenosvinos** [comment]
Fixed. Thanks!
