### ISSUE TITLE
Typo? Inconsistency?

### ISSUE THREAD

**Issue by DrSchimke** [dddinphp/ddd-in-php-book-issues#7]
9.2.1 Forcing Invariants

_In a Domain model with a `Forum` and `Article` entities, where `Article` is an Aggregate of `Forum`, publishing an Article could be something like..._

In the following examples, the thing is no longer called `Article`, but ``Post`. It may be more clear to chose one term.

Another question regarding the above quote: _is an Aggregate of Forum_ – What do you mean by this? I see there an Aggregate, whose Aggregate Root seems to be `Forum` and `Article`/`Post` being part of the aggregate. Maybe I use the words different than you do?

10.4 Collection-Oriented Repositories

Typo: _If for example we have the following Domain ~~Modal~~**Model**_

And then in your example in the constructor, you have parameters `$anId`, `$aBody` and `$createdAt` – why some are prefixed with an article and other are not? I personally dislike the attitude  of naming parameters different than properties. This comes from java and is in PHP unnecessary, where we can distinguish between `$this->id` and `$id`.

**Comment by carlosbuenosvinos** [comment]
@keyvanakbary, could you fix it? Thanks!

**Comment by keyvanakbary** [comment]
@DrSchimke Great report, I'll fix it. Thanks! :)

**Comment by keyvanakbary** [comment]
@DrSchimke woah, this has been hanging around for a long time. I'm very sorry. We've fixed all your suggestions.

On the _an_ article topic, this is a style choice. Along with the original DDD authors (Evans / Vernon) we believe this way improves the way we think about domain concepts and the Ubiquitous Language that drives the design.

Thanks and sorry for the delay.
