### ISSUE TITLE
Factory Method pattern -> Template Method pattern

### ISSUE THREAD

**Issue by Djuki** [dddinphp/ddd-in-php-book-issues#70]
On PDF page 158:

> Event publication to its own method by applying the Factory Method pattern¹¹³.
> According to Wikipedia¹¹⁴:

Instead of "Factory Method pattern" it should be "Template Method pattern". It already linking the right Wikipedia link to template method pattern.

**Comment by carlosbuenosvinos** [comment]
Thanks! You're now in the acknowledgments :)
