### ISSUE TITLE
Code typo

### ISSUE THREAD

**Issue by JPuigV** [dddinphp/ddd-in-php-book-issues#75]
In Architectural Styles > Synchronizing the Write Model with the Read Model, in the code after "The following code shows how the flow between the projector and the events would appear", line 25 should be:
`$projector->project($events);`
instead of
`$projector->project($event);`
And same in the next example with amqplib (line 31).

**Comment by carlosbuenosvinos** [comment]
Thanks, fixed! Can you provide your name and last name, please?

**Comment by JPuigV** [comment]
Jordi Puig ;)

**Comment by carlosbuenosvinos** [comment]
Cool! you are now in the Acknowledgements section :)

**Comment by JPuigV** [comment]
Great! Thank you!
