### ISSUE TITLE
UpdateOrderAmountService execute method not using orderId variable

### ISSUE THREAD

**Issue by dfvalero** [dddinphp/ddd-in-php-book-issues#76]
Hey! Congrats for the book!

There is a small mistake in the Anemic Domain Models vs. Rich Domain Models chapter.

There is a class called UpdateOrderAmountService trying to update the amount of an order, but instead of using the orderId you are forcing to find the order with the id = 1.

Thanks for all the knowledge!

**Comment by keyvanakbary** [comment]
Nice! Fixed it in master, should be already in Leanpub 👍 👏

I have included you in the Acknowledgments as "David Fernández", I hope I got it right from Google 😂

Thanks a lot!
