### ISSUE TITLE
Uncredited excerpt from Martin Fowler

### ISSUE THREAD

**Issue by marcverney** [dddinphp/ddd-in-php-book-issues#77]
The _Metaphor_ section at the beginning of the _Domain events_ chapter is clearly a copy/paste from Martin Fowler´s [Domain events page](https://martinfowler.com/eaaDev/DomainEvent.html)
![dddinphp-domain-events-fowler](https://user-images.githubusercontent.com/6585350/28869006-99416dfe-777b-11e7-9dae-01f4ab346371.PNG)

This text should be presented to the reader as a quote, and credited to its original author.

**Comment by keyvanakbary** [comment]
Wow! Nasty, we rely a lot on original quotes by brilliant authors and this is totally unfair. It totally went unnoticed. I just fixed it, should be already available in Leanpub 👍

You are already in the Acknowledgements so I can't add you again. Thanks a lot!

**Comment by marcverney** [comment]
Keyvan, your change from two weeks ago does not seem to be reflected in LeanPub. Nothing has changed there.

**Comment by keyvanakbary** [comment]
Facepalm, I forgot to hit the button “publish new version”. Now is available to download, I checked it myself.

Thanks for the heads up! 👍

**Comment by marcverney** [comment]
Ok I see it now. I was not aware that this same text was in POEAA too, though. I saw it on [Fowler's website](https://martinfowler.com/eaaDev/DomainEvent.html), only with slight differences.
