### ISSUE TITLE
Declaration must be compatible with Service

### ISSUE THREAD

**Issue by IvixLabs** [dddinphp/ddd-in-php-book-issues#78]
Page 103 contains 
`class SignInUserService implements Service {
....
public function execute(SignInUserRequest $request)
{
....
`
later 
`interface Service
{
public function execute($request);
}`

but php does not allows overrides function declaration except __construct.

Seem need avoid common service interface or modify all construction.

**Comment by keyvanakbary** [comment]
Hey, thanks for the issue. I'm not able to find the issue in the book, do you have the latest version of it?
