### ISSUE TITLE
Page 10 mvc pattern figure

### ISSUE THREAD

**Issue by hoseinz3** [dddinphp/ddd-in-php-book-issues#83]
in this figure why model connected to view ?

**Comment by keyvanakbary** [comment]
In classic MVC it's usual to pass the _model_ to the view as a parameter (imagine passing a `User` model to the view). Without DTO's this couples the view to the model. The view has to know which methods and attributes the model has in order to render itself.

I hope it helps :)

**Comment by hoseinz3** [comment]
@keyvanakbary it was acceptable for me that view depends on the model but I think that model never depends on the view.( in page 10 figure model depends on the view)

**Comment by theUniC** [comment]
Hi @hoseinz3,

Initially MVC was used mainly for desktop GUIs. In those MVC implementations, the *View* was subscribed (through an Observer pattern) to *Model* changes. That's the reason why there's a relation between the *Model* and The *View*.

Hope it helps!
Christian.

**Comment by hoseinz3** [comment]
@theUniC thank you :)
