### ISSUE TITLE
Multiple typos in paragraph from the Repositories section

### ISSUE THREAD

**Issue by marcverney** [dddinphp/ddd-in-php-book-issues#86]
At the end of the Persistence-oriented Repositories chapter, there's the following paragraph:

> When using an ORM, save method is simpler because the ORM takes care about to know if the
Entity is new or an existing one. If you decide to go without ORM, it is your responsibility to check
if the Entity already exists. Another option is to segregate your PostRepository interface with an
insert and update method. Implementations that do not depend on , such RedisPostRepository
can perform the same operation in insert and update. However, we recommend you to push for
the save approach that leaks no implementations details to the business logic.

Errors:
- "save method is simpler" => *the* save method is simpler
- "takes care about to know" => takes care *of knowing*
- "Implementations that do not depend on" => "Implementations that do not depend on *an ORM*
- "such RedisPostRepository" => such *as* RedisPostRepository, (note the comma added after "RedisPostRepository" too)

**Comment by keyvanakbary** [comment]
💥 Fixed and live. Thanks for your contribution, again 😊 🙌
