### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by nicoSWD** [dddinphp/ddd-in-php-book-issues#9]
Hey guys,

great book, I enjoyed it very much! Looking forward to reading the missing 40%.

I found a couple of typos, however.
#### 3.4.5 Replaceability
- If Carlos then changes the month in his hire date to May, Christian’s hire date changes ~~to~~ _too_.
#### 3.4.6 Side-Effect-Free Behaviour
- Code free of side-effects is easy to understand, easy to test and less ~~error prone~~ _error-prone_.
#### 3.5 Basic Types
- Although $a and $b are different variables, stored low-level in different memory ~~location~~ _locations_...
#### 3.7.1.1 Embedded Value with an ad-hoc ORM
- However, everything is not as easy as it seems~~, let’s~~_. Let's_ try to fetch the persisted Product with...
- An Entity should be created with the new operator just once in its ~~life~~ _lifetime_. (or _lifecycle_)
#### 3.7.3.1 PostgreSQL and JSONB
- Well, now you can~~, a~~ _. A_s of PostgreSQL version 9.4**_,**_ support for JSONB¹⁹ has been added.
#### 3.8 Wrap-up
- In order to handle persistence within ~~an~~ _a_ DDD application...
#### 4.1 Introduction
- A person has always an identity and it’s always the same regarding ~~it’s~~ _their_ name, or
  document identifier.
- An order in an e-commerce system. In that context every new order created has ~~it’s~~ _its_ own
  identity and it’s the same over time
#### 4.2 Objects vs Primitive ~~t~~**_T**_ypes
- Most of the time the identity of an entity ~~it’s~~ _is_ represented as a primitive type
- With value objects**,** equality ~~operation~~ **operations** can be modelled and encapsulated ~~on its~~ _in their_ own ~~class~~ **classes**, making concepts go from implicit to explicit.
#### 4.5 Testing entities
- private function __construct($a~~n~~Status)
#### 4.6.1 Attribute Validation
- Some people understand validation as the process ~~where-by~~ _whereby_...
- if (~~is_empty~~ _empty_($username)) {
#### 4.7 Wrap-up
- We’ve ~~showed~~ _shown_ several ways of providing identity
- Sometimes the ~~I~~_i_dentity fits a domain concept an**_d**_ you could model it inside your domain
#### 5.1 Introduction
- Operate ~~on only~~ _only on_ types belonging to the domain
#### 5.3 Domain Services
- Throughout conversation**_s**_ with...
- Domain services don’t hold any kind of state by ~~itself~~ _themselves_...
#### 5.6 Anemic Domain Models vs Rich Domain Models
- Or in the case ~~to update~~ _of updating_ an order amount
#### 5.7 Wrap-up
- As we~~â€™~~**_'**_ve seen
#### 6.7.1 Messaging
- We’ll see **_this**_ in more detail ~~this~~ in the “Integrating Bounded Contexts” chapter.
#### 7.1 Structuring Code in Modules
- As Evans ~~point on~~ _points out in_ the blue book, Modules are a way to communicate...

(**The blue book** probably referrers to _Domain-Driven Design: Tackling Complexity in the Heart of Software_?)
#### 7.1.1 Modules in the Infrastructure Layer
- ...will rot fast and ~~becoming~~ _become_ a mess...
#### 7.1.1.1 Mixing Different Technologies
- Our general advice here, is that this kind of situations are ~~an~~ **a** smell...
#### 8.1 Introduction
- You can fetch a User using its Repository~~,~~ **_.**_

Keep up the good work! 👍

**Comment by carlosbuenosvinos** [comment]
Value Objects fixes applied. Thanks.

**Comment by carlosbuenosvinos** [comment]
Entities too.

**Comment by carlosbuenosvinos** [comment]
Everything done

**Comment by nicoSWD** [comment]
👍
